### ISSUE TITLE
개발환경 구축

### ISSUE THREAD

**Issue by smarthome-hanium** [Eye-Remocon/MeetingNote#7]
## 가상환경 설치(Windows, Mac인 경우)
- [Ubuntu 20.04](https://releases.ubuntu.com/20.04/ubuntu-20.04.2.0-desktop-amd64.iso) 이미지 다운로드
- VirtualBox 설치
- Ubuntu 20.04 이미지로 인스턴스 생성

## HomeEdge 프로젝트 설치
- [How to build](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/docs/platforms/x86_64_linux/x86_64_linux.md#how-to-build) 가이드 확인하여 환경 설정

**Comment by smarthome-hanium** [comment]
@Seunghui98 HomeEdge 개발환경 구축을 한 번 해보시겠어요? 하시면서 어려운 점, 궁금한 점 있으면 코멘트 남겨주세요!

**Comment by Seunghui98** [comment]
멘토님 ! VirtualBox 설치해서 그 위에 Ubuntu 설치하고 도커랑 고언어까지 설정한 뒤에 환경변수까지 지정했습니다. 근데
./build.sh 여기서부터 파일이 없다고 안되는데 이 파일이 어디 디렉토리에 있을까요 ?
그리고 edge-orchestration를 도커에 load 했을 때 계속 REPOSITORY 이름이 <none>이라고 설정되어서
REPOSITORY를 edge-orchestration라고 변경했는데 이렇게 하는 게 맞을까요..?

**Comment by t25kim** [comment]
@Seunghui98 개발환경 구축하시느라 고생 많으셨어요. [build.sh](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/build.sh) 파일은 edge-home-orchestration-go 폴더에 바로 있는 파일이에요. git clone으로 받으면 폴더 바로 안에 있는 것이라고 보시면 됩니다. 
docker load라고 하셔서.. 혹시 [quick-start](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/docs/platforms/x86_64_linux/x86_64_linux.md#quick-start) 부분을 하신건가요? Edge Orchestration 릴리즈 이미지를 다운로드 하여 작업 하시는 것보다는 소스코드를 빌드해서 하시는게 좋을 것 같아서 quick-start는 무시하시고 [How to build](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/docs/platforms/x86_64_linux/x86_64_linux.md#how-to-build) 부분을 따라서 하시면 좋을 것 같아요.

**Comment by smarthome-hanium** [comment]
@Seunghui98 개발환경 구축하시느라 고생 많으셨어요. [build.sh](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/build.sh) 파일은 edge-home-orchestration-go 폴더에 바로 있는 파일이에요. git clone으로 받으면 폴더 바로 안에 있는 것이라고 보시면 됩니다. 
docker load라고 하셔서.. 혹시 [quick-start](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/docs/platforms/x86_64_linux/x86_64_linux.md#quick-start) 부분을 하신건가요? Edge Orchestration 릴리즈 이미지를 다운로드 하여 작업 하시는 것보다는 소스코드를 빌드해서 하시는게 좋을 것 같아서 quick-start는 무시하시고 [How to build](https://github.com/lf-edge/edge-home-orchestration-go/blob/master/docs/platforms/x86_64_linux/x86_64_linux.md#how-to-build) 부분을 따라서 하시면 좋을 것 같아요.
